In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.972
Model:                            OLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     540.7
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           5.43e-70
Time:                        19:44:55   Log-Likelihood:                -365.44
No. Observations:                 100   AIC:                             744.9
Df Residuals:                      93   BIC:                             763.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -23.1715      7.102     -3.263      0.002     -37.274      -9.069
X1             1.1656      0.112     10.406      0.000       0.943       1.388
X2             1.5993      0.053     30.192      0.000       1.494       1.704
X3             1.1394      0.084     13.621      0.000       0.973       1.305
X4             0.6669      0.114      5.840      0.000       0.440       0.894
X5            -2.0392      0.049    -41.275      0.000      -2.137      -1.941
X6            -1.0214      0.087    -11.688      0.000      -1.195      -0.848
==============================================================================
Omnibus:                        2.193   Durbin-Watson:                   2.299
Prob(Omnibus):                  0.334   Jarque-Bera (JB):                1.801
Skew:                          -0.325   Prob(JB):                        0.406
Kurtosis:                       3.097   Cond. No.                         536.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [8]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.976
Model:                            OLS   Adj. R-squared:                  0.973
Method:                 Least Squares   F-statistic:                     300.4
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           2.51e-65
Time:                        19:44:55   Log-Likelihood:                -357.05
No. Observations:                 100   AIC:                             740.1
Df Residuals:                      87   BIC:                             774.0
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -36.8580     10.770     -3.422      0.001     -58.264     -15.452
X1             1.1539      0.109     10.611      0.000       0.938       1.370
X2             1.6499      0.054     30.802      0.000       1.543       1.756
X3             1.1194      0.082     13.693      0.000       0.957       1.282
X4             0.6965      0.112      6.213      0.000       0.474       0.919
X5            -2.0568      0.048    -42.962      0.000      -2.152      -1.962
X6            -0.9574      0.086    -11.129      0.000      -1.128      -0.786
X7            -0.0437      0.119     -0.368      0.714      -0.280       0.193
X8            -0.0345      0.047     -0.729      0.468      -0.128       0.059
X9             0.0334      0.083      0.404      0.687      -0.131       0.198
X10            0.0745      0.113      0.657      0.513      -0.151       0.300
X11            0.0945      0.047      2.021      0.046       0.002       0.187
X12            0.2593      0.083      3.128      0.002       0.095       0.424
==============================================================================
Omnibus:                        0.202   Durbin-Watson:                   2.448
Prob(Omnibus):                  0.904   Jarque-Bera (JB):                0.044
Skew:                           0.049   Prob(JB):                        0.978
Kurtosis:                       3.035   Cond. No.                     1.19e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.19e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.14297433,  1.64459004,  1.11189595,  0.68323658, -2.05420444,
       -0.95414206, -0.03305227, -0.03122934,  0.02322232,  0.05872349,
        0.0926401 ,  0.24930742])

In [10]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.04024766,  1.59730183,  1.04081382,  0.55337184, -2.03589426,
       -0.91896922, -0.        , -0.0090348 ,  0.        ,  0.        ,
        0.07432694,  0.16952982])

In [11]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.15248358,  1.6492695 ,  1.11845825,  0.69545961, -2.05631808,
       -0.95689218, -0.04394482, -0.03447504,  0.033153  ,  0.07464609,
        0.0944733 ,  0.25888904])

In [12]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.55063775,  1.20994181,  0.61178627,  0.31013487, -1.6679942 ,
       -0.58739106, -0.05536987, -0.01610291, -0.07073533,  0.11618899,
        0.07052716,  0.06310182])