In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.962
Model:                            OLS   Adj. R-squared:                  0.960
Method:                 Least Squares   F-statistic:                     392.1
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           1.00e-63
Time:                        19:02:54   Log-Likelihood:                -373.39
No. Observations:                 100   AIC:                             760.8
Df Residuals:                      93   BIC:                             779.0
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -43.7535      7.461     -5.864      0.000     -58.570     -28.937
X1             1.5968      0.134     11.914      0.000       1.331       1.863
X2             1.4692      0.060     24.454      0.000       1.350       1.589
X3             1.2367      0.097     12.730      0.000       1.044       1.430
X4             0.7847      0.122      6.412      0.000       0.542       1.028
X5            -2.0275      0.051    -39.532      0.000      -2.129      -1.926
X6            -0.9325      0.094     -9.876      0.000      -1.120      -0.745
==============================================================================
Omnibus:                        4.760   Durbin-Watson:                   2.179
Prob(Omnibus):                  0.093   Jarque-Bera (JB):                2.697
Skew:                           0.168   Prob(JB):                        0.260
Kurtosis:                       2.269   Cond. No.                         508.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [8]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.963
Model:                            OLS   Adj. R-squared:                  0.958
Method:                 Least Squares   F-statistic:                     188.9
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           7.42e-57
Time:                        19:14:36   Log-Likelihood:                -371.96
No. Observations:                 100   AIC:                             769.9
Df Residuals:                      87   BIC:                             803.8
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -42.2630     11.125     -3.799      0.000     -64.374     -20.152
X1             1.5934      0.139     11.496      0.000       1.318       1.869
X2             1.4626      0.062     23.431      0.000       1.339       1.587
X3             1.2550      0.101     12.453      0.000       1.055       1.455
X4             0.7889      0.129      6.129      0.000       0.533       1.045
X5            -2.0283      0.053    -38.588      0.000      -2.133      -1.924
X6            -0.9416      0.097     -9.695      0.000      -1.135      -0.749
X7             0.0694      0.128      0.541      0.590      -0.186       0.325
X8            -0.0133      0.056     -0.239      0.812      -0.124       0.098
X9            -0.1167      0.100     -1.166      0.247      -0.316       0.082
X10            0.0407      0.130      0.313      0.755      -0.217       0.299
X11           -0.0393      0.054     -0.729      0.468      -0.147       0.068
X12           -0.0294      0.099     -0.298      0.767      -0.226       0.167
==============================================================================
Omnibus:                        4.164   Durbin-Watson:                   2.100
Prob(Omnibus):                  0.125   Jarque-Bera (JB):                2.841
Skew:                           0.244   Prob(JB):                        0.242
Kurtosis:                       2.334   Cond. No.                     1.04e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.58061656,  1.45919464,  1.24359852,  0.76963254, -2.02457275,
       -0.93253585,  0.0551373 , -0.01116676, -0.10621488,  0.0219051 ,
       -0.03616585, -0.02035702])

In [10]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.45494432,  1.43260601,  1.15789565,  0.62400463, -1.98679659,
       -0.86315309,  0.        , -0.        , -0.0319987 , -0.        ,
       -0.01449377, -0.        ])

In [11]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.59094038,  1.46214235,  1.25385439,  0.78755932, -2.02760989,
       -0.94092734,  0.06952431, -0.01322758, -0.11653358,  0.04033035,
       -0.03929612, -0.02933034])

In [12]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 6.48105706e-01,  1.11287932e+00,  6.66928538e-01,  2.33590952e-01,
       -1.54850423e+00, -5.54493830e-01,  7.14380195e-02,  3.45530772e-02,
       -3.75722252e-02, -4.50899553e-02, -3.52393017e-02,  1.54010017e-03])